# Generated by Django 3.2.7 on 2021-10-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'admin'), ('General', 'general')], default='General', max_length=120),
        ),
    ]
